MvcApplication1/Controllers/AdmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Globalization;
using System.Web.Mvc;
using MvcApplication1.Helpers;
using UxiEntities;
using System.Configuration;
using System.Net;


namespace MvcApplication1.Controllers
{

    public class AdmController : Controller
    {


        int sesionUsr = 0;
        string nombre = string.Empty;
        string tipousr = string.Empty;

        SeguridadUsr seguridad = new SeguridadUsr();
        //
        // GET: /Adm/

        public ActionResult Index()
        {

            try
            {
                sesionUsr = Session["idusuario"].ToString() != "" ? Convert.ToInt16(Session["idusuario"].ToString()) : 0;

                if (sesionUsr != 0)
                {

                    nombre = Session["Nombre"].ToString();
                    tipousr = Session["tipoUSR"].ToString();

                    UxiUsuariosEE Usuario = new UxiUsuariosEE();
                    Usuario = seguridad.Usuario(sesionUsr.ToString());

                    if (Usuario.isAutenticated == true && Usuario.IdRol == 2) return View();
                    else return View("Acceso");

                }


            }
            catch
            {
                return View("Acceso");
            }

            return View();




        }
        public ActionResult Usuarios()
        {


            try
            {
                sesionUsr = Session["idusuario"].ToString() != "" ? Convert.ToInt16(Session["idusuario"].ToString()) : 0;

                if (sesionUsr != 0)
                {

                    nombre = Session["Nombre"].ToString();
                    tipousr = Session["tipoUSR"].ToString();

                    UxiUsuariosEE Usuario = new UxiUsuariosEE();
                    Usuario = seguridad.Usuario(sesionUsr.ToString());

                    if (Usuario.isAutenticated == true && Usuario.IdRol == 2)
                    {
                        AdmUsrCs listUsr = new AdmUsrCs();
                        List<USP_GetUsuarioCuenta_EE> ListaResult = new List<USP_GetUsuarioCuenta_EE>();
                        ListaResult = listUsr.ListaUsuarios();


                        return View(ListaResult);
                    }
                    else return View("Acceso");

                }


            }
            catch
            {
                return View("Acceso");
            }

            return View();

        }



        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult actualizaUsuario(int idUsuario, int IdTipo, decimal saldo, bool verTarifas)
        {
            AdmUsrCs obj = new AdmUsrCs();
            obj.ActualizaUsuarioCuenta(idUsuario, IdTipo, saldo, verTarifas);
            return Json("");
        }

        public ActionResult Ordenes()
        {
            try
            {
                sesionUsr = Session["idusuario"].ToString() != "" ? Convert.ToInt16(Session["idusuario"].ToString()) : 0;

                if (sesionUsr != 0)
                {

                    UxiUsuariosEE Usuario = new UxiUsuariosEE();
                    Usuario = seguridad.Usuario(sesionUsr.ToString());
                    if (Usuario.isAutenticated == true)
                    {
                        string idUsuario = Session["idusuario"].ToString();

                        OrdenesUsuario _ordenesUsuario = new OrdenesUsuario();
                        //List<OrdenDeCompra> ordenesUsuario = new List<OrdenDeCompra>();
                        //ordenesUsuario = _ordenesUsuario.ListaOrdenes("0");

                        //obtiene la lista de estatus de las ordenes
                        ListaEstatus _estatusOrden = new ListaEstatus();
                        List<UxiEntities.EstatusOrden> listaEstatus = new List<UxiEntities.EstatusOrden>();
                        listaEstatus = _estatusOrden._listaEstatus();

                        nombre = Session["Nombre"].ToString();
                        ViewData["EstatusOrden"] = listaEstatus;
                        //ViewData["Ordenes"] = ordenesUsuario;
                        ViewBag.idUsuario = idUsuario;
                        ViewBag.NombreUsuario = nombre;

                        return View();
                       
                    }
                    return RedirectToAction("index");

                }


            }
            catch (Exception e)
            {
                return View("index");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Ordenes(string altField,string altFieldHasta, int estatus,string ordenCompra,string email)
        {
            try
            {
                sesionUsr = Session["idusuario"].ToString() != "" ? Convert.ToInt16(Session["idusuario"].ToString()) : 0;

                if (sesionUsr != 0)
                {

                    UxiUsuariosEE Usuario = new UxiUsuariosEE();
                    Usuario = seguridad.Usuario(sesionUsr.ToString());
                    if (Usuario.isAutenticated == true)
                    {
                        int IdOrden = 0;
                        string idUsuario = Session["idusuario"].ToString();
                        IdOrden = (ordenCompra == "" ? 0 : Convert.ToInt32(ordenCompra)) ;
                        altField = (altField == "" ? "00010101" : altField);
                        altFieldHasta = (altFieldHasta == "" ? "00010101" : altFieldHasta);
                        OrdenesUsuario _ordenesUsuario = new OrdenesUsuario();
                        List<OrdenDeCompra> ordenesUsuario = new List<OrdenDeCompra>();
                        ordenesUsuario = _ordenesUsuario.ListaOrdenes(IdOrden, altField, altFieldHasta,0, email);
                        if (estatus!=0)
                        {
                            ordenesUsuario = (from s in ordenesUsuario
                                      where s.IdEstatusOC == estatus
                                      select s).ToList();
                        }
                        //obtiene la lista de estatus de las ordenes
                        ListaEstatus _estatusOrden = new ListaEstatus();
                        List<UxiEntities.EstatusOrden> listaEstatus = new List<UxiEntities.EstatusOrden>();
                        listaEstatus = _estatusOrden._listaEstatus();

                        nombre = Session["Nombre"].ToString();
                        ViewData["EstatusOrden"] = listaEstatus;
                        ViewData["Ordenes"] = ordenesUsuario;
                        ViewBag.idUsuario = idUsuario;
                        ViewBag.NombreUsuario = nombre;

                        //return View();
                        return PartialView("_OrdenesAdm");
                    }
                    return RedirectToAction("index");

                }


            }
            catch (Exception e)
            {
                return View("index");
            }
            return View();
        }

        public ActionResult Servicios(int? ido)
        {
            List<Servicios> servicios = new List<Servicios>();
            Message msg = new Message();
            ListaServicios listServicios = new ListaServicios();
            try
            {
                sesionUsr = Session["idusuario"].ToString() != "" ? Convert.ToInt16(Session["idusuario"].ToString()) : 0;

                if (sesionUsr != 0)
                {
                    UxiUsuariosEE Usuario = new UxiUsuariosEE();
                    Usuario = seguridad.Usuario(sesionUsr.ToString());
                    if (Usuario.isAutenticated == false)
                    {
                        return View("Acceso");
                    }
                    
                    ViewData["listCategoria"] = listServicios.getCategorias();
                    if (ido == null)
                    {
                        msg.hasMessage = false;
                    }
                    else 
                    {
                        msg.hasMessage = true;
                        msg.strMessage = ido == 1 ? "¡Se agrego el servicio correctamente!" : "¡Se actualizo el servicio correctamente!";                        
                    }
                    ViewBag.Message = msg;
                }
            }
            catch
            {
                return View("Acceso");
            }
            
            return View(servicios);
        }
        [HttpPost]
        public ActionResult Servicios(string sta, string des, string idc)
        {
            List<Servicios> servicios = new List<Servicios>();
            ListaServicios listServicios = new ListaServicios();
            try
            {
                sesionUsr = Session["idusuario"].ToString() != "" ? Convert.ToInt16(Session["idusuario"].ToString()) : 0;

                if (sesionUsr != 0)
                {
                    UxiUsuariosEE Usuario = new UxiUsuariosEE();
                    Usuario = seguridad.Usuario(sesionUsr.ToString());
                    if (Usuario.isAutenticated == false)
                    {
                        return View("Acceso");
                    }
                    servicios = listServicios.getListaServicios(idc: idc, act: sta);
                    if (des != "")
                    {
                        servicios = (from s in servicios where s.Descripcion_Corta.Contains(des) select s).ToList();
                    }                            
                }
            }
            catch
            {
                return View("Acceso");
            }
            return PartialView("_listaServicios", servicios);
        }

        public ActionResult _detalleServicio(int? ids)
        {
            ListaServicios listServicios = new ListaServicios();
            Servicios servicio = listServicios.getDetalleServicio(ids: ids);
            ViewData["listCategoria"] = listServicios.getCategorias();
            return PartialView(servicio);
        }

MvcApplication1/Controllers/PlantillaController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class PlantillaController : Controller
    {
        //
        // GET: /Plantilla/

        public ActionResult Plantilla()
        {
            List<Producto> productos = new List<Producto>()
            {

            new Producto {Codigo = 1, Descripcion = "Descripción 1", Nombre = "Producto 1", Precio = 100m},
            new Producto {Codigo = 2, Descripcion = "Descripción 2", Nombre = "Producto 2", Precio = 200m},
            new Producto {Codigo = 3, Descripcion = "Descripción 3", Nombre = "Producto 3", Precio = 300m},
            new Producto {Codigo = 4, Descripcion = "Descripción 4", Nombre = "Producto 4", Precio = 400m}
            };
            return View(productos);
        }

    }
}

MvcApplication1/Views/Shared/EjemploForm.cshtml
@model MvcApplication1.Models.Producto
@{
    Layout = null;
}


@using (Html.BeginForm("EjemploForm", "index", FormMethod.Post)) //etiqueta form que va al controller de libros, la función de AltaLibro y con el metodo POST
{
    <label>Numero Saga</label>@Html.TextBoxFor(m => m.Nombre) <br />



    <button type="submit" class="btn btn-orange pull-right">SEND</button>

}

MvcApplication1/Views/Shared/Plantilla.cshtml
@model List<MvcApplication1.Models.Producto>
@{
    Layout = null;
}

<style type="text/css">
    .tg {
        border-collapse: collapse;
        border-spacing: 0;
        border-color: #999;
        width:100%;
    }

        .tg td {
            font-family: Arial, sans-serif;
            font-size: 14px;
            padding: 10px 5px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: #999;
            color: #444;
            background-color: #F7FDFA;
        }

        .tg th {
            font-family: Arial, sans-serif;
            font-size: 14px;
            font-weight: normal;
            padding: 10px 5px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: #999;
            color: #fff;
            background-color: #26ADE4;
        }

        .tg .tg-yw4l {
            vertical-align: top;
        }
</style>
<table class="tg">
    <tr>
        <th class="tg-031e">DESC</th>
        <th class="tg-yw4l">NOMBRE</th>
        <th class="tg-yw4l">PRECIO</th>
    </tr>
@foreach (var item in Model)
{
    <tr>
        <td class='tg-yw4l'> @item.Descripcion </td>
        <td class="tg-yw4l">@item.Nombre</td>
        <td class="tg-yw4l">@item.Precio</td>
    </tr>
    
     
}
</table>

MvcApplication1/Views/Shared/_LayoutAdm.cshtml
@{
    ViewBag.Title = "_LayoutAdm";
    string apiUX = System.Configuration.ConfigurationManager.AppSettings["apiUX"].ToString();

}

@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v3.12.1, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="~/assets/images/logo.png" type="image/x-icon">
    <meta name="description" content="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/assets/bootstrap-material-design-font/css/material.css">
    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="~/assets/et-line-font-plugin/style.css">
    <link rel="stylesheet" href="~/assets/tether/tether.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/animate.css/animate.min.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css" type="text/css">
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <link id="themecss" rel="stylesheet" type="text/css" href="//www.shieldui.com/shared/components/latest/css/light/all.min.css" />
    <script type="text/javascript" src="//www.shieldui.com/shared/components/latest/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="//www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    <script src="~/assets/js/canvasjs.min.js"></script>


    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-102252692-1', 'auto');
  ga('send', 'pageview');
    var _apiUX = @(Html.Raw(Json.Encode(apiUX)));                
    </script>

</head>
<body>
    <section id="ext_menu-6">

        <nav class="navbar navbar-dropdown navbar-fixed-top">
            <div class="container">

                <div class="mbr-table">
                    <div class="mbr-table-cell">

                        <div class="navbar-brand">

                            <a class="navbar-caption" href="/Adm/Index"><span class="mbri-mobile mbr-iconfont mbr-iconfont-btn"></span>UX iSolutions.com</a>
                        </div>

                    </div>
                    <div class="mbr-table-cell">

                        <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                            <div class="hamburger-icon"></div>
                        </button>

                        <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                            <li class="nav-item">@Html.ActionLink("USUARIOS", "Usuarios", "Adm", null, new { @class = "nav-link link" })</li>
                            <li class="nav-item">@Html.ActionLink("GENERAR ORDENES DE SERVICIO", "index", "Home", null, new { @class = "nav-link link" })</li>
                            <li class="nav-item">@Html.ActionLink("SERVICIOS","Servicios","Adm",null,new {@class = "nav-link link"})</li>
                            <li class="nav-item">@Html.ActionLink("ADMINISTRAR ORDENES", "Ordenes", "Adm", null, new { @class = "nav-link link" })</li>
                            <li class="nav-item">@Html.ActionLink("CERRAR SESIÓN", "CloseSesion", "Home", null, new { @class = "nav-link link" })</li>
                            <li class="nav-item"><a class="nav-link link" href="Home"></a></li>


                        </ul>
                        <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                            <div class="close-icon"></div>
                        </button>

                    </div>
                </div>
             
            </div>
            <div id="mensajesexp"></div>
        </nav>

    </section>

    <div class="modal btn-loader" id="whaithingpage" tabindex="-1" aria-hidden="true">
    </div>

    @RenderBody()



    <footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-n" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">

        <div class="container">
            <p class="text-xs-center">
                Copyright (c) @System.DateTime.Today.Year Incsoft consulting.
                <img src="https://micuenta.donweb.com/img/RapidSSL_SEAL-90x50.gif" alt="Sello de verificación RapidSSL" />
            </p>
        </div>
    </footer>
    <script src="~/assets/web/assets/jquery/jquery.min.js"></script>
    <script src="~/assets/tether/tether.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/smooth-scroll/smooth-scroll.js"></script>
    <script src="~/assets/viewport-checker/jquery.viewportchecker.js"></script>
    <script src="~/assets/jarallax/jarallax.js"></script>
    <script src="~/assets/dropdown/js/script.min.js"></script>
    <script src="~/assets/touch-swipe/jquery.touch-swipe.min.js"></script>
    <script src="~/assets/theme/js/script.js"></script>
    <script src="~/assets/formoid/incsoftScript.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script> 
    <input name="animation" type="hidden">

</body>
</html>

MvcApplication1/Views/Shared/_LayoutHome.cshtml
@{
    ViewBag.Title = "_LayoutHome";
    string apiUX = System.Configuration.ConfigurationManager.AppSettings["apiUX"].ToString();
}

@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
   
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v3.12.1, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="~/assets/images/logo.png" type="image/x-icon">
    <meta name="description" content="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/assets/bootstrap-material-design-font/css/material.css">
    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="~/assets/et-line-font-plugin/style.css">
    <link rel="stylesheet" href="~/assets/tether/tether.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/animate.css/animate.min.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css" type="text/css">
    <script src='https://www.google.com/recaptcha/api.js'></script>




    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-102252692-1', 'auto');
  ga('send', 'pageview');
        var _apiUX = @(Html.Raw(Json.Encode(apiUX)));
    </script>

</head>
<body>
    <section id="ext_menu-6">

        <nav class="navbar navbar-dropdown navbar-fixed-top">
            <div class="container">

                <div class="mbr-table">
                    <div class="mbr-table-cell">

                        <div class="navbar-brand">

                            <a class="navbar-caption" ><span class="mbri-mobile mbr-iconfont mbr-iconfont-btn"></span>UX iSolutions.com</a>
                        </div>

                    </div>
                    <div class="mbr-table-cell">

                        <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                            <div class="hamburger-icon"></div>
                        </button>

                        <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                            @*<li class="nav-item">@Html.ActionLink("MI CUENTA", "MiCuenta", "Home", null, new { @class = "nav-link link" })</li>*@
                            <li class="nav-item">@Html.ActionLink("NUEVA ORDEN", "index", "Home", null, new { @class = "nav-link link" })</li>
                            <li class="nav-item">@Html.ActionLink("MIS PEDIDOS", "MisPedidos", "Home", null, new { @class = "nav-link link" })</li>
                            @if (ViewBag.Tipousr == true)
                            {
                                <li class="nav-item">@Html.ActionLink("ADMINISTRACION", "Index", "Adm", null, new { @class = "nav-link link" })</li>
                            }
                            <li class="nav-item">@Html.ActionLink("MI CUENTA", "MiCuenta", "Home", null, new { @class = "nav-link link" })</li>
                            <li class="nav-item">@Html.ActionLink("CERRAR SESIÓN", "CloseSesion", "Home", null, new { @class = "nav-link link" })</li>




                            <li class="nav-item"><a class="nav-link link" href="Home"></a></li>

                            
                        </ul>
                        <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                            <div class="close-icon"></div>
                        </button>

                    </div>
                </div>

            </div>
            <div id="mensajesexp"></div>
        </nav>

    </section>

    <div class="modal btn-loader" id="whaithingpage" tabindex="-1" aria-hidden="true">
    </div>

    @RenderBody()



    <footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-n" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">

        <div class="container">
            <p class="text-xs-center">
                Copyright (c) @System.DateTime.Today.Year Incsoft consulting.
                <img src="https://micuenta.donweb.com/img/RapidSSL_SEAL-90x50.gif" alt="Sello de verificación RapidSSL" />
            </p>
        </div>
    </footer>
    <script src="~/assets/web/assets/jquery/jquery.min.js"></script>
    <script src="~/assets/tether/tether.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/smooth-scroll/smooth-scroll.js"></script>
    <script src="~/assets/viewport-checker/jquery.viewportchecker.js"></script>
    <script src="~/assets/jarallax/jarallax.js"></script>
    <script src="~/assets/dropdown/js/script.min.js"></script>
    <script src="~/assets/touch-swipe/jquery.touch-swipe.min.js"></script>
    <script src="~/assets/theme/js/script.js"></script>
    <script src="~/assets/formoid/incsoftScript.js"></script>
    <input name="animation" type="hidden">

</body>
</html>